string1 = str(input("Введите какой-нибудь тескст: "))
print(string1)
digit = int(input("Введите целое число: "))
print(digit)
drob = float(input("Введите нецелое число: "))
print("Ваш текст:", string1, "Ваше число:", digit, "Ваше дробное число:", drob)
